### ISSUE TITLE
How would you adapt this for packaging and deploying a production application?

### ISSUE THREAD

**Issue by kofno** [johnomarkid/elm-electron-webpack#3]
Thank you for this guide.

How would you adapt this code so that you could package this in an installer? Since the the webpack server won't be running on a client machine, what would you do to adapt this code for a production deploy?

**Comment by johnomarkid** [comment]
You wouldn't need the webpack server running because you won't be using hot reloading or any of the development tools. A production deploy will just read the final javascript file produced in /dist.

**Comment by kofno** [comment]
So, is there an env var we can toggle between loading the JS from the dev server and loading from dist/ ? Maybe update the index.html asset during the build process?

**Comment by johnomarkid** [comment]
in this guide there is not, but you can certainly create an env variable that loads either the file on the dev server or the file from /dist/bundle.js depending on whether the app is in development or production.

**Comment by kofno** [comment]
Cool. Thanks!
